spring: 
  datasource: 
    url:  jdbc:mysql://localhost:3306/mydb
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: update
      naming.strategy: org.hibernate.cfg.ImprovedNamingSrategy
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect